---
name: Publish Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Parameter to pass to `npm version` (e.g: 'patch', 'minor', 'major', 'prerelease', etc. - default: 'patch')"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: percona-platform/checkout@v2

      - uses: percona-platform/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: Configure git
        env:
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global url."https://percona-platform-robot:${WORKFLOW_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      - name: Clean up after tests
        run: git checkout -- tsconfig.json

      - name: Build package
        run: npm run build

      - name: Print the current branch
        run: git branch && echo "$GITHUB_REF"

      - name: Bump version
        env:
          VERSION: ${{ github.event.inputs.version || 'prerelease' }}
        run: npm version $VERSION

      - name: Publish latest version
        if: ${{ env.VERSION != 'prerelease' }}
        run: npm publish --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish next version
        if: ${{ env.VERSION == 'prerelease' }}
        run: npm publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Print the current branch
        run: git branch && echo "$GITHUB_REF"

      - name: Push the new version
        run: git push origin --follow-tags
